# Generated by Django 3.1.1 on 2020-10-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.order'),
        ),
    ]
