# Generated by Django 3.1.1 on 2020-10-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201007_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cust',
        ),
    ]
