# Generated by Django 3.1.1 on 2020-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
