# Generated by Django 3.1.1 on 2020-10-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_remove_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
