# Generated by Django 3.1.1 on 2020-10-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
